name: package-nuget

on:
    workflow_call:
  
jobs:
  call-workflow:
    uses: JimIBrown/actions-workflows/.github/workflows/versioning.yml@main
  build-package-nuget:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: NuGet Configure sources
        run: |
          dotnet nuget add source --username JimIBrown --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/JimIBrown/index.json"
      
      - name: Install dependencies
        working-directory: ./src
        run: dotnet restore

      - name: Build
        working-directory: ./src
        run: |
            echo "BuildConfiguration: $BuildConfiguration"
            dotnet build --configuration $BuildConfiguration --no-restore
      - name: Test with the dotnet CLI
        working-directory: ./src
        run: dotnet test --no-build

      - name: Pack
        if: ${{ github.event_name != 'pull_request' }}
        working-directory: ./src
        run: dotnet pack **/*.csproj --configuration $BuildConfiguration --no-build --output ./pkg/

      - name: Push
        if: ${{ github.event_name != 'pull_request' }}
        working-directory: ./src
        run: dotnet nuget push pkg/*.nupkg --source https://nuget.pkg.github.com/${{ github.REPOSITORY_OWNER}}/index.json --api-key ${GITHUB_TOKEN}

      - name: Publish-Artifact
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./src/pkg/*.nupkg
            
